# Generated by Django 4.0.3 on 2022-03-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_rename_pessoas_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',), 'verbose_name': 'nome'},
        ),
    ]
