# Generated by Django 4.0.3 on 2022-03-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
