# Generated by Django 4.0.3 on 2022-03-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ('id',), 'verbose_name': 'nomes de receita'},
        ),
    ]
